import { Providers } from './providers'
import './globals.css'

export const metadata = {
  title: 'Aviato',
  description: 'A playground for using react.js to practice building stuff. Generated by create next app, extended by others',
}

export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
  return (
    <html lang='en'>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
